### ISSUE TITLE
positive or negative PPM supported?

### ISSUE THREAD

**Issue by onki69** [normbxl/USB_PPM_Joystick#1]
Hi,

I tried to use this adapter on an old Graupner mc15. The HID device is recocnized properly at the PC but no axis is giving any movement. A PPM sigfnal is present at pin8.
Is a positive or negative signal required at pin8 or is there any software possibility to "invert" the signal?

Thanks for this nice project anyway.

Onki

**Comment by onki69** [comment]
This issue is solved. The adapter definitely needs a positive PPM signal.
Since I was able to identify such a signal in my old transmitter I can now use the Adapter.
It might be a good Idea to have a configuration possibility ina future version to choose pos. or neg. PPM signal.
Working with Win7 the input is not very smooth but it works on Win 10 nicely.
Onki

**Comment by normbxl** [comment]
Hey,
nice to hear it works. Sorry, had not time to look into the issue. The jitter is due to the non-interrupt implementation to measure the pulse-width. Perhaps a newer version of V-USB, which does not use both external pin-int's could solve that problem.
