### ISSUE TITLE
Working after inverting my PPM signal

### ISSUE THREAD

**Issue by myself248** [normbxl/USB_PPM_Joystick#3]
My config: Radiolink T8S transmitter and R8EF receiver, in PPM mode (blue LED means SBUS on ch1, PPM on ch2). Receiver powered from 5v USB, but its signal outputs are natively 3.3v, so that's nice. 

I'm using an Arduino Uno, which is a mega328p. It enumerates on USB just fine, but I coudn't get any change in the readings when I moved the sticks. 

Finally, I compared the oscilloscope trace of my PPM signal with some other images I found online, and... it appears to be inverted? So I grabbed the first NPN transistor I could find, a big ol' TIP31, and made a simple inverter. Et voila, suddenly it works! Joysticks wiggle, simulators simulate! 

I'm pretty sure I could swap a bunch of HIGHs and LOWs in the code and do the same thing, but I'm more confident with transistors than code. ;)

**Comment by normbxl** [comment]
Good to hear it still works. Indeed I could add a macro that takes care the polarity issue.
